apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tpps2g3mj-nodejs 
  janus-idp.io/tekton: tpps2g3mj-nodejs
  backstage.io/kubernetes-id: tpps2g3mj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tpps2g3mj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  